baseurl = "https://yanlinlin.cn/"
title = "颜林林的个人网站"
paginate = 20
googleAnalytics = "G-P6SH63QQPQ"

[taxonomies]
  type = "types"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = true
lineNos = true
style = "monokailight"

[permalinks]
posts = "/:year/:month/:day/:slug/"
page = "/:slug/"

[[menu.main]]
weight = 10
name = "博客"
url = "/"

[[menu.main]]
weight = 20
name = "公众号"
url = "/public/"

[[menu.main]]
weight = 30
name = "朋友圈"
url = "/moments/"

[[menu.main]]
weight = 40
name = "作品"
url = "/works/"

[[menu.main]]
weight = 50
name = "学习"
url = "/study/"

[[menu.main]]
weight = 60
name = "简历"
url = "/cv/"

[[menu.main]]
weight = 90
name = "关于"
url = "/about/"
